### ISSUE TITLE
Skip button (Vertagen, Aussitzen)

### ISSUE THREAD

**Issue by mdrie** [neustartklima/ich-kann-klima#111]
We decided to allow the player to do nothing / skip a decision / pass no law. A button "Aussitzen" would trigger a next step in the game without passing a law. The `NewYear.ts` law also has to be modified, since it counts passed laws.

**Comment by jschirrmacher** [comment]
An alternative would be to add a "law" to each set which does just that. Some of the events have a list of laws, and these have such (look for "AbstandsregelnFuerWindkraftWieBisher" as an example). This way, it is more "context sensitive".

So, the "skip button" solution should only be used for random law sets.

**Comment by mdrie** [comment]
Once a do-nothing law is accepted, it will not be proposed again. We would have to change this logic quite a bit to change that. A general "Aussitzen" button would be easy to understand, quite funny, also available, when there is no event and - i think - easier and faster to implement. And we keep the list of laws a little smaller. There will be many...
