### ISSUE TITLE
Game over is not shown

### ISSUE THREAD

**Issue by mdrie** [neustartklima/ich-kann-klima#125]
Currently, there is no indication that the game is over.

Findings:
- I found this, because sometimes the proposed laws drop down to the table and one can only guess from Peek values that a game-over event happened.
- Driving the game to a definitve game-over (e.g. popularity <= 0) results in the same effect.
- Appending `/over` to the URL results in a long wait and then in a reload of the URL without the `/over`.
- Sometimes the laws drop to the table and in the developer tools page "Vue" it can be seen that the list of events is emptied. (Maybe not related.)

**Comment by jschirrmacher** [comment]
Actually, there seems to be some code to be vanished. There is a store action `gameOver` and it is dispatched in several events, but I don't find a code location using the `over` property in the game.

I think the `GamePage` should `watch` the property and redirect to `/over`. I'll try that, but would be happy to have a test for that as well. It would have to enforce a game becoming over and should expect the `GameOver` page to be displayed. Again, I'm thinking of an automatic play mode running a list of events and decisions...

**Comment by jschirrmacher** [comment]
PR #135 should help us test that.
