### ISSUE TITLE
Use pseudo random numbers

### ISSUE THREAD

**Issue by jschirrmacher** [neustartklima/ich-kann-klima#127]
If we would use pseudo randomness, we could use the list of events and laws in the game to "replay" it, and so debug a game that was played by someone and produced unexpected results.
Maybe [jsrand](https://github.com/DomenicoDeFelice/jsrand) can help

**Comment by jschirrmacher** [comment]
I close this issue in favor of #133

**Comment by mdrie** [comment]
Oh, I thought that this might be a prerequisite for #133 and also for another thing, we want to achieve: Being able to replay / reproduce any game played by a player. The latter could by yet another issue. Or we put it all in #133 which is quite a task then.

**Comment by jschirrmacher** [comment]
Ok, you're right. The good thing is, we can re-open.
