### ISSUE TITLE
Save game status on server

### ISSUE THREAD

**Issue by jschirrmacher** [neustartklima/ich-kann-klima#13]
As a player, I want to save my game to continue later on another computer.

It might not be necessary to ask the player for their e-mail address or to create a password. It might be sufficient to create a link, which can be copied and transported separately (by e-mail, of course, but also on an USB stick, for example).

**Comment by mdrie** [comment]
Hast Du das jetzt nicht mit dem Backend fertig?

**Comment by jschirrmacher** [comment]
Ja, sollte passen.
