### ISSUE TITLE
Check DSGVO conformity

### ISSUE THREAD

**Issue by mdrie** [neustartklima/ich-kann-klima#141]

**Comment by jschirrmacher** [comment]
[eRecht24](https://www.e-recht24.de/artikel/datenschutz/8451-hinweispflicht-fuer-cookies.html#richtlinie) sagt:

> Die DSGVO regelt die Probleme "Tracking und Cookies" nicht ausdrücklich. Das sollte die ePrivacy-Verordnung tun, die zeitgleich mit der DSGVO in Kraft treten sollte. Nach mehrmaligem Verschieben tritt sie vielleicht Ende 2021 in Kraft. Wenn überhaupt. Webseitenbetreiber orientieren sich aktuell an dem, was die einzelnen Datenschutzbehörden und die Datenschutzkonferenz vorgeben und was der EuGH und in der Folge der BGH im Jahr 2020 dazu entschieden haben

und weiter:

> Benötigen alle Cookies eine Einwilligung?
>
> Nein, Sie benötigen nicht für sämtliche Cookies eine Zustimmung in Form der Einwilligung der Nutzer Ihrer Website. Das TTDSG sagt:
> 
> Die Einwilligung brauchen Sie nicht, wenn Sie dem Nutzer Ihren Dienst sonst nicht zur Verfügung stellen kann. Sprich: Sie brauchen keine Einwilligung für technisch notwendige Cookies.
> 
> Die entspricht dem, was der EuGH dazu entscheiden hat und was die einzelnen Datenschutzbehörden und die Datenschutzkonferenz (DSK) vorgeben. Deren Auffassung ist aktuell:
> 
> Nicht für alle Cookies benötigt man eine Einwilligung.
> - Session-Cookies, Cookies für Logins oder Warenkörbe, die keine Daten weitergeben, können vom berechtigten Interesse des Webseitenbetreibers abgedeckt sein.
> - Tracking und Werbe-Cookies von Drittanbietern benötigen eine Einwilligung.
>
> Das sind also vor allem Cookies, die für die eigentlichen Funktionen der Webseite nicht zwingend notwendig sind und die Daten dann gegebenenfalls mit anderen Daten und Diensten verknüpfen oder teilen.

Dann gibt es noch den Datenschutz. Da geht es um personenbezogene Daten, also alles, was sich auf konkrete Personen bezieht. Die müssen besonders geschützt werden. Da wir noch nicht einmal den Namen noch die E-Mail-Adresse verwenden, bleibt als einziges personenbezogene Datum die IP-Adresse. Die könnte höchstens in Log-Dateien zur Nachvollziehbarkeit von Fehlern auf dem Server auftauchen. Die werden aber nach kurzer Zeit gelöscht und damit wieder Datenschutzkonform.

**Comment by jschirrmacher** [comment]
Ja, so sehe ich das zumindest mit meinem laienhaften Verständnis.
