### ISSUE TITLE
Game flow: how can a user put the laws aside?

### ISSUE THREAD

**Issue by jschirrmacher** [neustartklima/ich-kann-klima#182]
As a user, I want to see the room (especially the window and the news from the television) without the laws to be in the way.

I think, the should be automatically put aside after selecting one of them, or when I sit it out. I, personally, would prefer to take them up again when I need them, maybe they could also be automatically shown again after I close a news message.

**Comment by mdrie** [comment]
Automatically dropping the laws to the table was REALLY annoying. I would prefer that they can be dropped by the player by clicking on them.

**Comment by mdrie** [comment]
I actually tried that while fixing the event stuff in conjunction with #118, but it did not work immediately as I expected and i focused on the other stuff.
