### ISSUE TITLE
Inconsistencies in game-play

### ISSUE THREAD

**Issue by mdrie** [neustartklima/ich-kann-klima#190]
Dinge, die beim Spielen aufgefallen sind:
* [x] SolarAufAllenDaechernVerpflichtend wird nie vorgeschlagen.
* [x] Die finanzielle Situation ist keine Herausforderung im Spiel. Vielleicht sollten einige Gesetze mehr kosten?
* [x] PRInnenminister und Plagiatsaffaere kommen immer direkt hintereinander.
* [x] PRKohleindustrie kommt zu früh.
* [x] Winkraftforschung kommt mehrfach.
* [x] EnergieStrategie sollte früher kommen.
* [x] SolarEntergie kommt kaum.
* [x] Wenn man es so gerade nicht geschafft hat, passt nicht so richtig "Die CO2-Emmissionen sind explodiert, das Budget ist aufgebraucht. Hätte die AfD nicht besser hinbekommen."
* [x] Der Text von Hitzehölle sollte auf das aufgebrauchte Budget eingehen. Die genannten Konsequenzen treten sicher erst weiter in der Zukunft ein.
* [x] ForschungUndEntwicklungStromspeicherung wird wieder vorgeschlagen, obwohl ich es gerade akzeptiert hatte
* [x] Gesetz "CO2 Preis Erhöhen" wird mir angeboten, nachdem ich bereits "WirksamerCO2Preis" angenommen habe
* [x] Gesetz "CO2 Preis Erhöhen" wird mir auch angeboten, nachdem ich dann "VollerCO2Preis" angenommen habe
* [x] Einerseits "Klimaneutral !!!", also Spiel gewonnen, andererseits "Das Spiel ist leider zu Ende" und "...Emmissionen sind explodiert..."

**Comment by jschirrmacher** [comment]
* [] ForschungUndEntwicklungStromspeicherung wird wieder vorgeschlagen, obwohl ich es gerade akzeptiert hatte
* [] Gesetz "CO2 Preis Erhöhen" wird mir angeboten, nachdem ich bereits "WirksamerCO2Preis" angenommen habe
* [] Gesetz "CO2 Preis Erhöhen" wird mir auch angeboten, nachdem ich dann "VollerCO2Preis" angenommen habe

**Comment by mdrie** [comment]
* [ ] Einerseits "Klimaneutral !!!", also Spiel gewonnen, andererseits "Das Spiel ist leider zu Ende" und "...Emmissionen sind explodiert..."
