### ISSUE TITLE
Laws for Mobility

### ISSUE THREAD

**Issue by mdrie** [neustartklima/ich-kann-klima#45]

**Comment by jschirrmacher** [comment]
In the meantime, we have:
- several "Nahverkehr" laws
- several "Fernverkehr" laws
- a "LadeinfrastrukturAusbauen"law
- an "ElektromobilitaetFoerdern" law
- a "TempolimitAufAutobahnen" event
- several "Tempolimit" laws
- a "WasserstoffmobilitaetFoerdern" law
- a "DienstwagenPrivilegAbschaffen" law
- a "DieselPrivilegAbgeschaffen" law
- an "AusbauVonStrassen" law
- an "AutosInInnenstaedtenVerbieten" law

I think, I can close this issue now in good conscience.
