### ISSUE TITLE
Model, laws, and events for wind energy

### ISSUE THREAD

**Issue by mdrie** [neustartklima/ich-kann-klima#57]

**Comment by jschirrmacher** [comment]
Isn't this already solved by #61 ?

**Comment by jschirrmacher** [comment]
In the meantime, we have:
- an event "WindkraftAusschreibung"
- multiple variants of "Abstandsregeln" laws
- multiple variants of "Ausschreibungsverfahren" laws
- a "WindkraftVereinfachen" law

I think, I can close this issue now in good conscience
