### ISSUE TITLE
Provide fields for integration of content from document(s).

### ISSUE THREAD

**Issue by mdrie** [neustartklima/ich-kann-klima#73]
- [x] Type `Sources` - structured list of sources of the used information.
- [x] Type `Details` - for information possibly displayed in the game, when a user requests it.
- [x] Type `Internals` - for internal information never to display to the user.
- [x] Exend Law by `sources`, `details`, and `internals`.
- [x] Extend Event by `sources`, `details`, and `internals`.
- [x] New type / class for the fields of `BaseParams` to with `type`, `unit` (replaces unit in `PeekOptions`), `writable`, `sources`, `details`, and `internals`.
 - This will possibly tie together the 3 places, where the definition of `BaseParams` currently happens.

**Comment by mdrie** [comment]
@jschirrmacher What do you think?

**Comment by jschirrmacher** [comment]
Sounds great!
I imagine that `Sources` might be a simple list of URLs, while `Details` and `Internals` might be simple `string` arrays.

**Comment by jschirrmacher** [comment]
I also often forget to adapt `PeekOptions` when I add new `BaseParams`. Would be helpful if types and values would be converge at a single location.
